stages:
    - general
    - lang_check

.caching:
    cache:
        key: "$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR"
        policy: pull
        paths:
            - clang/out/

General Test:
    extends: .caching
    stage: general
    tags:
        - pycounter
    script:
        - echo "This is the general test stage."
        - scm/scripts/ci/general_ci.sh

Bash Test:
    extends: .caching
    stage: lang_check
    tags:
        - pycounter
    script:
        - echo "This is the Bash Script CI check stage."
        - scm/scripts/ci/bash_ci.sh

CMake Test:
    extends: .caching
    stage: lang_check
    tags:
        - pycounter
    script:
        - echo "This is the CMake CI check stage."
        - scm/scripts/ci/cmake_ci.sh

C Language Test:
    extends: .caching
    stage: lang_check
    tags:
        - pycounter
    script:
        - echo "This is the C language CI check stage."
        - scm/scripts/ci/clang_ci.sh

Python Test:
    extends: .caching
    stage: lang_check
    tags:
        - pycounter
    script:
        - echo "This is the python CI check stage."
        - scm/scripts/ci/python_ci.sh
